## PLOTTING UTILS DICTIONARIES

## PLOT LABELS, COLORMAPS, AND Y-LIMITS or COLORBAR LIMITS and LIMITS
## SCALES (LOG, LINEAR, or SYMLOG)
plot_labels = {
        'rho': {'log': True,
                'lim': (1e4, 1e15),
                'cmap': 'viridis',
                'label': r'$\rho$ [g$\cdot$cm$^{-3}$]'},
        'rho_max': {'log': True,
                'lim': (1e4, 1e15),
                'cmap': 'viridis',
                'label': r'$\rho$ [g$\cdot$cm$^{-3}$]'},
        'MHD_energy': {'log': True,
                'lim': (1e24, 1e35),
                'cmap': 'nipy_spectral',
                'label': r'$E$ [erg]'},
        'VX': {'log': True,
               'lim': (-1e10, 5e10),
               'cmap': 'Spectral_r',
               'label': r'$v_r$ [cm$\cdot$s$^{-1}$]'},
        'VY': {'log': True,
               'lim': (-1e10, 1e10),
               'cmap': 'Spectral_r',
               'label': r'$v_\theta$ [cm$\cdot$s$^{-1}$]'},
        'VZ': {'log': True,
               'lim': (1e7, 1e10),
               'cmap': 'cividis',
               'label': r'$v_\phi$ [cm$\cdot$s$^{-1}$]'},
        'YE': {'log': False,
               'lim': (0.0, 0.5),
               'cmap': 'gist_rainbow',
               'label': r'Y$_e$'},
        'YN': {'log': False,
               'lim': (0, 1.0),
               'cmap': 'gist_rainbow',
               'label': r'Y$_N$'},
        'ERR': {'log': False,
                'lim': (0, 1),
                'cmap': 'seismic',
                'label': r'Error'},
        'LRTZ': {'log': False,
                 'lim': (1, 1.1),
                 'cmap': 'gist_rainbow',
                 'label': r'$\gamma$'},
        'DENS': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'EINT': {'log': True,
                 'lim': (1e24, 1e35),
                 'cmap': 'nipy_spectral',
                 'label': r'$E_{\mathrm{int}}$ [erg]'},
        'ENTH': {'log': True,
                 'lim': (1e25, 1e36),
                 'cmap': 'gist_stern',
                 'label': r'$H$ [erg'},
        'PELE': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'TELE': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'NELE': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'PION': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'TION': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'NION': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'VELX': {'log': True,
                 'lim': (-1e10, 5e10),
                 'cmap': 'Spectral_r',
                 'label': r'$v_r$ [cm$\cdot$s$^{-1}$]'},
        'VELY':  {'log': True,
                  'lim': (-1e10, 1e10),
                  'cmap': 'Spectral_r',
                  'label': r'$v_\theta$ [cm$\cdot$s$^{-1}$]'},
        'VELZ':  {'log': True,
                  'lim': (1e7, 1e10),
                  'cmap': 'cividis',
                  'label': r'$v_\phi$ [cm$\cdot$s$^{-1}$]'},
        'T': {'log': False,
              'lim': (0, 40),
              'cmap': 'inferno',
              'label': r'T [MeV]'},
        'ENTR': {'log': False,
                 'lim': (1.5, 25),
                 'cmap': 'gist_rainbow_r',
                 'label': r'S [k$_b$/bry]'},
        'GAMM': {'log': False,
                 'lim': (0.5, 3.5),
                 'cmap': 'cividis',
                 'label': r'$\Gamma$'},
        'HEAT': {'log': True,
                 'lim': (-1e31, 1e32),
                 'cmap': 'Spectral_r',
                 'label': r'$Q_\nu$ [erg]'},
        'DELP': {'log': True,
                 'lim': (1e4, 1e15),
                 'cmap': 'viridis',
                 'label': r''},
        'JX': {'log': True,
               'lim': (-1e24, 1e24),
               'cmap': 'coolwarm',
               'label': r'$j_r$ [g$\cdot$cm$^{2}\cdot$s$^{-2}$]'},
        'JY': {'log': True,
               'lim': (-1e20, 1e20),
               'cmap': 'Spectral_r',
               'label': r'$j_\theta$ [g$\cdot$cm$^{2}\cdot$s$^{-2}$]'},
        'JZ': {'log': True,
               'lim': (-1e23, 1e23),
               'cmap': 'seismic',
               'label': r'$j_\phi$ [g$\cdot$cm$^{2}\cdot$s$^{-2}]$'},
        'PGAS': {'log': True,
                 'lim': (1e25, 1e34),
                 'cmap': 'gist_rainbow_r',
                 'label': r'P$_\mathrm{gas}$ [dyn cm$^{-2}$]'},
        'VSOUND': {'log': True,
                   'lim': (1e8, 1e10),
                   'cmap': 'nipy_spectral',
                   'label': r'v$_\mathrm{sound}$ [cm$\cdot$s$^{-1}$]'},
        'X_n': {'log': False,
                'lim': (0, 1),
                'cmap': 'cividis',
                'label': r'X$_n$'},
        'X_p': {'log': False,
                'lim': (0, 1),
                'cmap': 'viridis', 'label': r'X$_p$'},
        'X_alpha': {'log': False,
                    'lim': (0, 1), 
                    'cmap': 'plasma',
                    'label': r'X$_\alpha$'},
        'X_h': {'log': False,
                'lim': (0, 1),
                'cmap': 'magma',
                'label': r'X$_h$'},
        'Abar': {'log': True,
                 'lim': (4, 80),
                 'cmap': 'gist_rainbow_r',
                 'label': r'$\bar{A}$'},
        'Zbar': {'log': False,
                 'lim': (1, 34), 
                 'cmap': 'nipy_spectral', 
                 'label': r'$\bar{Z}$'},
        'CPOT_e': {'log': True, 
                   'lim': (0.1, 300), 
                   'cmap': 'coolwarm', 
                   'label': r'$\mu_e$ [erg$\cdot$g$^{-1}$]'},
        'CPOT_n': {'log': True, 
                   'lim': (-2e2, 3e3), 
                   'cmap': 'bwr', 
                   'label': r'$\mu_n$ [erg$\cdot$g$^{-1}$]'},
        'CPOT_p': {'log': True, 
                   'lim': (-2e2, 3e3), 
                   'cmap': 'seismic', 
                   'label': r'$\mu_p$ [erg$\cdot$g$^{-1}$]'},
        'CPOT_nu': {'log': True, 
                    'lim': (-2e2, 3e3), 
                    'cmap': 'Spectral_r', 
                    'label': r'$\mu_\nu$ [erg$\cdot$g$^{-1}$]'},
        'BHEX': {'log': True, 
                 'lim': (1e4, 1e15), 
                 'cmap': 'viridis', 
                 'label': r'$\rho$ [g cm$^{-3}$]'},
        'NUEX': {'log': True, 
                 'lim': (-1e39, 1e39), 
                 'cmap': 'Spectral_r', 
                 'label': r'F$_{\nu_e,r}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUEY': {'log': True, 
                 'lim': (-1e38, 1e38), 
                 'cmap': 'Spectral_r', 
                 'label': r'F$_{\nu_e,\theta}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUEZ': {'log': True, 
                 'lim': (-1e38, 1e38), 
                 'cmap': 'Spectral_r', 
                 'label': r'F$_{\nu_e,\phi}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUEE': {'log': True, 
                 'lim': (1e25, 1e34), 
                 'cmap': 'viridis', 
                 'label': r'E$_{\nu_e}$ [erg$\cdot$ s$^{-1}$]'},
        'NUAX': {'log': True, 
                 'lim': (-1e39, 1e39), 
                 'cmap': 'Spectral_r', 
                 'label': r'F$_{\overline{\nu}_e,r}$' \
                     r' [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUAY': {'log': True, 'lim': (-1e38, 1e38),
                 'cmap': 'Spectral_r',
                 'label': r'F$_{\overline{\nu}_e,\theta}$' \
                     r' [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUAZ': {'log': True,
                 'lim': (-1e38, 1e38),
                 'cmap': 'Spectral_r',
                 'label': r'F$_{\overline{\nu}_e,\phi}$' \
                     r' [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUAE': {'log': True, 
                 'lim': (1e25, 1e34),
                 'cmap': 'viridis',
                 'label': r'E$_{\overline{\nu}_e}$ [erg$\cdot$ s$^{-1}$]'},
        'NUXX': {'log': True,
                 'lim': (-1e39, 1e39),
                 'cmap': 'Spectral_r',
                 'label': r'F$_{\nu_x,r}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUXY': {'log': True,
                 'lim': (-1e38, 1e38),
                 'cmap': 'Spectral_r', 
                 'label': r'F$_{\nu_x,\theta}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUXZ': {'log': True,
                 'lim': (-1e38, 1e38),
                 'cmap': 'Spectral_r',
                 'label': r'F$_{\nu_x,\phi}$ [$\#_\nu\cdot$ s$^{-1}$]'},
        'NUXE': {'log': True,
                 'lim': (1e25, 1e34),
                 'cmap': 'viridis',
                 'label': r'E$_{\nu_x}$ [erg$\cdot$ s$^{-1}$]'},
        'BX': {'log': True,
               'lim': (-1e15, 1e15),
               'cmap': 'coolwarm',
               'label': r'B$_r$ [G]'},
        'BY': {'log': True,
               'lim': (-1e15, 1e15),
               'cmap': 'coolwarm',
               'label': r'B$_\theta$ [G]'},
        'BZ': {'log': True,
               'lim': (-1e15, 1e15),
               'cmap': 'coolwarm',
               'label': r'B$_\phi$ [G]'},
}

## PLOT LABELS FOR X-AXIS
xaxis_labels = {'radius': 'R [km]',
                'theta': r'$\theta$ [rad]',
                'phi': r'$\phi$ [rad]',
                'time': 't [s]'
                }