import os

def check_file_to_load(path):
    if path.endswith('.hdf5') or path.endswith('.h5') or path.endswith('.hdf'):
        return 'hdf5'
    elif not os.path.exists(path):
        return 'sim'

def convert_name(name):
    name_dict = {
      'rho': 'rho', 'rho_max': 'rho_max', 'rhom': 'rho_max',
      'mhd_energy': 'MHD_energy', 'mhd': 'MHD_energy', 'mhd_e': 'MHD_energy',
      'conserved_energy': 'MHD_energy', 'cons_ene': 'MHD_energy',
      'radial_velocity': 'radial_velocity', 'vr': 'radial_velocity', 
      'vx': 'radial_velocity',
      'theta_velocity': 'theta_velocity', 'vtheta': 'theta_velocity',
      'vy': 'theta_velocity',
      'phi_velocity': 'phi_velocity', 'vphi': 'phi_velocity', 
      'vz': 'phi_velocity',
      'soundspeed': 'soundspeed', 'cs': 'soundspeed', 'csound': 'soundspeed',
      'omega': 'omega', 'w': 'omega',
      'pressure': 'gas_pressure', 'p': 'gas_pressure', 'pgas': 'gas_pressure',
      'temperature': 'temperature', 't': 'temperature', 'temp': 'temperature',
      'enthalpy': 'enthalpy', 'h': 'enthalpy', 'enth': 'enthalpy',
      'adiabatic_index': 'adiabatic_index', 'gamma': 'adiabatic_index',
      'lorentz_factor': 'lorentz', 'lorentz': 'lorentz',
      'gravitational_potential': 'gravitational_potential', 
      'phi': 'gravitational_potential', 'gpot': 'gravitational_potential',
      'gravitational_energy': 'gravitational_energy',
      'grav_e': 'gravitational_energy', 'grav_ene': 'gravitational_energy',
      'internal_energy': 'internal_energy', 'eint': 'internal_energy',
      'neutrino_heating': 'nu_heat', 'nu_heat': 'nu_heat',
      'ye': 'Ye', 'electron_fraction': 'Ye',
      'neutron_fraction': 'neutron_fraction', 'Xn': 'neutron_fraction',
      'proton_fraction': 'proton_fraction', 'Xp': 'proton_fraction',
      'alpha_fraction': 'alpha_fraction', 'Xa': 'alpha_fraction',
      'heavy_fraction': 'heavy_fraction', 'Xh': 'heavy_fraction',
      'abar': 'Abar', 'average_atomic_mass': 'Abar',
      'zbar': 'Zbar', 'average_atomic_number': 'Zbar',
      'electron_chemical_potential': 'electron_chemical_potential', 
      'cpot_e': 'electron_chemical_potential', 
      'mue': 'electron_chemical_potential',
      'neutron_chemical_potential': 'neutron_chemical_potential',
      'cpot_n': 'neutron_chemical_potential', 
      'mun': 'neutron_chemical_potential',
      'proton_chemical_potential': 'proton_chemical_potential',
      'cpot_p': 'proton_chemical_potential',
      'mup': 'proton_chemical_potential',
      'neutrino_chemical_potential': 'neutrino_chemical_potential',
      'cpot_nu': 'neutrino_chemical_potential',
      'mnu': 'neutrino_chemical_potential',
      'error': 'error', 'eos_error': 'error', 'err': 'error',
      'magnetic_field_x': 'magnetic_fields_0', 'bx': 'magnetic_fields_0',
      'magnetic_field_y': 'magnetic_fields_1', 'by': 'magnetic_fields_1',
      'magnetic_field_z': 'magnetic_fields_2', 'bz': 'magnetic_fields_2',
      'poloidal_magnetic_fields': 'poloidal_magnetic_fields', 
      'bpol': 'poloidal_magnetic_fields',
      'toroidal_magnetic_fields': 'toroidal_magnetic_fields', 
      'btor': 'toroidal_magnetic_fields',
      'alfven_velocity': 'alfven_velocity', 'va': 'alfven_velocity',
      
      
    }

def return_index(hydro_dict, name):
    convert_dict = {
        'RHO': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_RH']},
        'ENE': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_EN']},
        'VX': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_VX']},
        'VY': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_VY']},
        'VZ': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_VZ']},
        'YE': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_YE']},
        'YN': {'type': 'hydro/data', 'index': hydro_dict['hydro']['I_YN']},
        'ERR': {'type': 'thd/data', 'index': hydro_dict['thd']['I_EOSERR']},
        'LRTZ': {'type': 'thd/data', 'index': hydro_dict['thd']['I_LRTZ']},
        'DENS': {'type': 'thd/data', 'index': hydro_dict['thd']['I_DENS']},
        'EINT': {'type': 'thd/data', 'index': hydro_dict['thd']['I_EINT']},
        'ENTH': {'type': 'thd/data', 'index': hydro_dict['thd']['I_ENTH']},
        'PELE': {'type': 'thd/data', 'index': hydro_dict['thd']['I_PELE']},
        'TELE': {'type': 'thd/data', 'index': hydro_dict['thd']['I_TELE']},
        'NELE': {'type': 'thd/data', 'index': hydro_dict['thd']['I_NELE']},
        'PION': {'type': 'thd/data', 'index': hydro_dict['thd']['I_PION']},
        'TION': {'type': 'thd/data', 'index': hydro_dict['thd']['I_TION']},
        'NION': {'type': 'thd/data', 'index': hydro_dict['thd']['I_NION']},
        'VELX': {'type': 'thd/data', 'index': hydro_dict['thd']['I_VELX']},
        'VELY': {'type': 'thd/data', 'index': hydro_dict['thd']['I_VELY']},
        'VELZ': {'type': 'thd/data', 'index': hydro_dict['thd']['I_VELZ']},
        'T': {'type': 'thd/data', 'index': hydro_dict['thd']['I_TMPR']},
        'ENTR': {'type': 'thd/data', 'index': hydro_dict['thd']['I_ENTR']},
        'GAMM': {'type': 'thd/data', 'index': hydro_dict['thd']['I_GAMM']},
        'HEAT': {'type': 'thd/data', 'index': hydro_dict['thd']['I_HEAT']},
        'DELP': {'type': 'thd/data', 'index': hydro_dict['thd']['I_DELP']},
        'JX': {'type': 'thd/data', 'index': hydro_dict['thd']['I_SMOMX']},
        'JY': {'type': 'thd/data', 'index': hydro_dict['thd']['I_SMOMY']},
        'JZ': {'type': 'thd/data', 'index': hydro_dict['thd']['I_SMOMZ']},
        'PGAS': {'type': 'thd/data', 'index': hydro_dict['thd']['I_PGAS']},
        'VSOUND': {'type': 'thd/data', 'index': hydro_dict['thd']['I_CSND']},
        'X_n': {'type': 'thd/data', 'index': hydro_dict['thd']['I_COMP'][0]},
        'X_p': {'type': 'thd/data', 'index': hydro_dict['thd']['I_COMP'][1]},
        'X_alpha': {'type': 'thd/data', 'index':
                    hydro_dict['thd']['I_COMP'][2]},
        'X_h': {'type': 'thd/data', 'index': hydro_dict['thd']['I_COMP'][3]},
        'Abar': {'type': 'thd/data', 'index': hydro_dict['thd']['I_COMP'][4]},
        'Zbar': {'type': 'thd/data', 'index': hydro_dict['thd']['I_COMP'][5]},
        'CPOT_e': {'type': 'thd/data', 'index': 
                   hydro_dict['thd']['I_CPOT'][0]},
        'CPOT_n': {'type': 'thd/data', 'index': 
                   hydro_dict['thd']['I_CPOT'][1]},
        'CPOT_p': {'type': 'thd/data', 'index': 
                   hydro_dict['thd']['I_CPOT'][2]},
        'CPOT_nu': {'type': 'thd/data', 'index': 
                    hydro_dict['thd']['I_CPOT'][3]},
        'BHEX': {'type': 'thd/data', 'index': hydro_dict['thd']['I_BHEX']},
        'NUEE': {'type': 'neutrinogrey/egrey', 'index': [0, 0] },
        'NUEX': {'type': 'neutrinogrey/egrey', 'index': [0, 1] },
        'NUEY': {'type': 'neutrinogrey/egrey', 'index': [0, 2] },
        'NUEZ': {'type': 'neutrinogrey/egrey', 'index': [0, 3] },
        'NUAE': {'type': 'neutrinogrey/egrey', 'index': [1, 0] },
        'NUAX': {'type': 'neutrinogrey/egrey', 'index': [1, 1] },
        'NUAY': {'type': 'neutrinogrey/egrey', 'index': [1, 2] },
        'NUAZ': {'type': 'neutrinogrey/egrey', 'index': [1, 3] },
        'NUXE': {'type': 'neutrinogrey/egrey', 'index': [2, 0] },
        'NUXX': {'type': 'neutrinogrey/egrey', 'index': [2, 1] },
        'NUXY': {'type': 'neutrinogrey/egrey', 'index': [2, 2] },
        'NUXZ': {'type': 'neutrinogrey/egrey', 'index': [2, 3] },
        'BX': {'type': 'mag_vol/data', 'index': 0},
        'BY': {'type': 'mag_vol/data','index': 1},
        'BZ': {'type': 'mag_vol/data', 'index': 2},
        }
    return convert_dict[name]